version: "2"
services:
  web:
    build: .
    ports:
      - "8080:3000"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27018:27017"
